### ISSUE TITLE
[SPIKE] Investigate, what localisation service is the best for us

### ISSUE THREAD

**Issue by alexslkgit** [skylab-main/ios#29]
**_Description:_**

ChatGPT, надає наступний список найпопулярніших сервісів які допомагають з локалізацієб проекту: OneSky, PhraseApp и Transifex. А також: Memsource, Smartling.

Також можете погуглити які ще є варінти. Критерії оцінки:

1. Сервіс має дозволити контролювати список локалізаційних строк. Щоб я як PO міг відкрити сайт та побачити які строки є в проекті, які строки вже локалізовані, які ще ні. 

3. В сервісі має бути можливість легко додавати мови. Наприклад в нас є англійська мова і 150 локалізаційних файлів. Я додаю в сервісі розділ "німецька локалізація". Я очікую, що всі 150 локалізаційних строк будуть вже скопійовані в німецький список, який ми зможемо відправити на локалізацію і легко вписати в цей список переклади.

4. Інтеграція з додатком. Цей сервіс має інтергруватися в додаток напряму (SPM/CocoaPods), або вміти інтегруватися до нашого репозиторія і автоматично оновлювати локалізаційні файли. Наприклад ми додали нові строки локалізації на сайті сервісу. Натискаємо кнопку і всі вони вигружаються напряму в репозиторій, чи напряму в проект.

**_Acceptance criteria:_**

Знайдний зручний сервіс локалізації, про який є відповіді по всім пунктам зазначеним вище.

Або підготована порівняльна таблиця сервісів, де порівнюються параметри, зазначені вище.

**_Notes:_**

Реалізація задачі буде в окремій задачі, коли ми погодимо конкретний сервіс для її виконання

**Comment by EvseevIvan** [comment]
[Click](https://docs.google.com/document/d/1U7TagZ5mvmKZxCPUx6vA_jinjtp8JwY7AxfUzy0sA24/edit)
