### ISSUE TITLE
[Documentation] Write "Creating feature toggle" page

### ISSUE THREAD

**Issue by alexslkgit** [skylab-main/ios#36]
**_Description:_**

Дивіться інформацію в notes. Для цієї задачі вже створена [сторінка в github wiki](https://github.com/skylab-main/ios/wiki/Feature-toggle)

**_Acceptance criteria:_**

На сторінці документації описаний процесс створення feature toggle, включаючи дії на сайті Firebase і код для додавання feature toggle в проект

**_Notes:_**

Написання документіції - невідʼємна частина роботи для програміста, що працює в професійній команді! Зазвичай вона пишеться англійською, щоб вона була доступна для членів команди з будь-якої країни. Але наша документація стосується навчання студентів з України, тому якщо вам так зручніше, є опція писати українською.

Мета написання документації в тому, щоб програмісти що працюють або будуть працювати з вами на цьому проекті могли швидко розібратися в тому як працює проект, або конкретна фіча. 

Тому в документації має бути весь набір корисної інформації по конретній технології, який може включати:

1. Посилання на матеріали для того щоб розібратися в конкретній технології (прохання додавати посилання тільки перевірені і прочитані матеріали).

2. Пошагову інструкцію, як виконати якусь дію на сайті (Посилання 1).

3. Пошагову інструкцію, як працювати з технологією в коді. В такому випадку прохання використовувати "вставки коду" в документацію, а не скріншоти.

_____________________

Для написання документації відкрийте сторінку [github wiki](https://github.com/skylab-main/ios/wiki) та створіть сторінку за назвлю вашої теми. Також ви можете подивитися[ інструкцію створену на Scribe ](https://scribehow.com/shared/Github_Workflow___3T39K13RgCjg1njjQfvEQ)

Посилання 1:
Є безкоштовне розширення для Chrome, яке допомагає створювати документацію автоматично. Ви не маєте робити скріншоти чи описувати, що ви натиснули, Scribe зробить все за вас. 
Будь ласка, ознайомтеся з цим інструментом [на цьому короткому відео](https://www.youtube.com/watch?v=QSZspGUoOrA)
[Встановити розширення для chrome ](https://chrome.google.com/webstore/detail/scribe-%E2%80%94-documentation-so/okfkdaglfjjjfefdcppliegebpoegaii
)

**Comment by EvseevIvan** [comment]
[Click](https://docs.google.com/document/d/1U7TagZ5mvmKZxCPUx6vA_jinjtp8JwY7AxfUzy0sA24/edit?usp=sharing)
