### ISSUE TITLE
[Documentation] Create documentation page about RxSwift.

### ISSUE THREAD

**Issue by alexslkgit** [skylab-main/ios#37]
**_Description:_**

Документація має охоплювати тільки той код, що був вже написаний з RxSwift і необхідну базу для розуміння цього коду. Ви можете додати лінки на перевірені ресурси, або описати своїми словами механізм роботи Rx, з картинками/схемами/визначеннями і т д. На ваш розсуд, просто другий варіант вам допоможе краще зрозуміти що ви ж робите

[Докладніше про написання документації.](https://github.com/skylab-main/ios/wiki/%D0%A9%D0%BE-%D1%82%D0%B0%D0%BA%D0%B5-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D1%96%D1%8F,-%D1%8F%D0%BA-%D0%B2%D0%BE%D0%BD%D0%B0-%D0%BF%D0%B8%D1%88%D0%B5%D1%82%D1%8C%D1%81%D1%8F-%D1%96-%D0%BD%D0%B0%D0%B2%D1%96%D1%89%D0%BE)

**_Acceptance criteria:_**

На сторінці документації описаний процесс створення feature toggle, включаючи дії на сайті Firebase і код для додавання feature toggle в проект

**_Notes:_**

Написання документіції - невідʼємна частина роботи для програміста, що працює в професійній команді! Зазвичай вона пишеться англійською, щоб вона була доступна для членів команди з будь-якої країни. Але наша документація стосується навчання студентів з України, тому якщо вам так зручніше, є опція писати українською.

Мета написання документації в тому, щоб програмісти що працюють або будуть працювати з вами на цьому проекті могли швидко розібратися в тому як працює проект, або конкретна фіча. 

Тому в документації має бути весь набір корисної інформації по конретній технології, який може включати:

1. Посилання на матеріали для того щоб розібратися в конкретній технології (прохання додавати посилання тільки перевірені і прочитані матеріали).

2. Пошагову інструкцію, як виконати якусь дію на сайті (Посилання 1).

3. Пошагову інструкцію, як працювати з технологією в коді. В такому випадку прохання використовувати "вставки коду" в документацію, а не скріншоти.

_____________________

Для написання документації відкрийте сторінку [github wiki](https://github.com/skylab-main/ios/wiki) та створіть сторінку за назвлю вашої теми. Також ви можете подивитися[ інструкцію створену на Scribe ](https://scribehow.com/shared/Github_Workflow___3T39K13RgCjg1njjQfvEQ)

Посилання 1:
Є безкоштовне розширення для Chrome, яке допомагає створювати документацію автоматично. Ви не маєте робити скріншоти чи описувати, що ви натиснули, Scribe зробить все за вас. 
Будь ласка, ознайомтеся з цим інструментом [на цьому короткому відео](https://www.youtube.com/watch?v=QSZspGUoOrA)
[Встановити розширення для chrome ](https://chrome.google.com/webstore/detail/scribe-%E2%80%94-documentation-so/okfkdaglfjjjfefdcppliegebpoegaii
)

**Comment by SerhiiMolodets** [comment]
pls check [here](https://github.com/skylab-main/ios/wiki/RxSwift)
